### ISSUE TITLE
Ritoplz v2.0.0

### ISSUE THREAD

**Issue by bukinoshita** [ritoplz/ritoplz#143]
## Pages

- [x] Add settings page ([#210](https://github.com/ritoplz/ritoplz/issues/210))

## Components

- [x] Add TextInput component ([#211](https://github.com/ritoplz/ritoplz/issues/211))
- [ ] Add SocialButton component ([#212](https://github.com/ritoplz/ritoplz/issues/212))
- [ ] Add UiLink component ([#213](https://github.com/ritoplz/ritoplz/issues/213))
- [x] Add UiButton component ([#214](https://github.com/ritoplz/ritoplz/issues/214))
- [x] Add Row component ([#217](https://github.com/ritoplz/ritoplz/issues/217))
- [x] Add Fieldset component ([#218](https://github.com/ritoplz/ritoplz/issues/218))
- [x] Add Badge component ([#219](https://github.com/ritoplz/ritoplz/issues/219))
- [ ] Add UiSelect component ([#224](https://github.com/ritoplz/ritoplz/issues/224))
- [ ] Add Header component ([#225](https://github.com/ritoplz/ritoplz/issues/225))

**Comment by bukinoshita** [comment]
Close bc of [this](https://github.com/ritoplz/ritoplz/projects/2)
